services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_mng
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - ./insert_users_final.sql:/docker-entrypoint-initdb.d/insert_users_final.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  auth:
    build:
      context: ./auth
    container_name: auth
    depends_on:
      mysql:
        condition: service_healthy   # ✅ healthcheck 기반
    ports:
      - "8080:8080"
    networks:
      - backend

  kafka:
    image: bitnami/kafka:3.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    networks:
      - backend

  kakao:
    build:
      context: ./kakao
    container_name: kakao
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend: