spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_mng?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true

# SEND Kakao
external:
  kakao:
    url: http://localhost:8081/kakaotalk-messages
